version: "3.8"
services:
  backend:
    image: "cariocaphil/spring-react-fullstack:19.10.2021.17.14.5"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev