version: "3.8"
services:
  backend:
    image: "cariocaphil/spring-react-fullstack:9.12.2021.18.1.56"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev