version: "3.8"
services:
  backend:
    image: "cariocaphil/spring-react-fullstack:22.10.2021.13.22.9"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev