version: "3.8"
services:
  backend:
    image: "cariocaphil/spring-react-fullstack:24.10.2021.22.57.23"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev